### ISSUE TITLE
dati per un uso locale

### ISSUE THREAD

**Issue by pigreco** [BikeItaly/stressbicyclemapitaly#5]
ottimo lavoro, grazie per la condivisione.
ma se volessi utilizzare i dati in locale, dove posso scaricare i dati con l'attributo che classifica lo stress dei percorsi?

grazie

**Comment by napo** [comment]
ciao
come scritto il lavoro deriva da quello di Bike Ottawa e, da loro repository, si trova il progetto iniziale.
Per aiutarti a semplificare fa un salto in quest'altro dove ho un po' fatto ordine
https://github.com/napo/trentocyclestressmap
